# Offense count: 2
Lint/UselessAssignment:
  Exclude:
    - 'examples/07_markdown_layout/example.rb'
    - 'spec/bobkit/watcher_spec.rb'

# Offense count: 1
# Configuration parameters: CountAsOne.
RSpec/ExampleLength:
  Max: 10

# Offense count: 10
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: implicit, each, example
RSpec/HookArgument:
  Exclude:
    - 'spec/bobkit/assets_spec.rb'
    - 'spec/bobkit/coffee_bridge_spec.rb'
    - 'spec/bobkit/i18n_bridge_spec.rb'
    - 'spec/bobkit/location_options_spec.rb'
    - 'spec/bobkit/markdown_bridge_spec.rb'
    - 'spec/bobkit/scope_options_spec.rb'
    - 'spec/bobkit/slim_bridge_spec.rb'
    - 'spec/bobkit/slim_options_spec.rb'
    - 'spec/bobkit/watcher_spec.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Style/ExpandPathArguments:
  Exclude:
    - 'bobkit.gemspec'

# Offense count: 1
Style/MissingRespondToMissing:
  Exclude:
    - 'lib/bobkit/scope.rb'

# Offense count: 8
Style/MixinUsage:
  Exclude:
    - 'bin/*'
    - 'spec/spec_helper.rb'
    - 'examples/01_basic/example.rb'
    - 'examples/02_multiple_pages/example.rb'
    - 'examples/03_options/example.rb'
    - 'examples/04_locales/example.rb'
    - 'examples/05_watcher/example.rb'
    - 'examples/06_markdown/example.rb'
    - 'examples/07_markdown_layout/example.rb'

# Offense count: 1
# Configuration parameters: AllowedMethods.
# AllowedMethods: respond_to_missing?
Style/OptionalBooleanParameter:
  Exclude:
    - 'lib/bobkit/scope.rb'
